/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle_de_lubrificantes;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ENGEMAQ
 */
public class Estoque_lubrificante extends javax.swing.JFrame {

    /**
     * Creates new form estoque_lubrificante
     */
    public Estoque_lubrificante() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/controle_de_lubrificantes/g891.png")).getImage());
        popular_combo_lubrificantes();
    }
    
     public void buscar_estoque_lub(){//buscar o estoque do lubrificante selecionado
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        
           
        try {
            ps = con.prepareStatement("SELECT * FROM public.lubrificantes where nome_lub = ?;");
            ps.setString(1, combo_lubrificante2.getSelectedItem().toString());
            rs = ps.executeQuery();
            
            while(rs.next()){
                label_ultimo_estoque.setText(String.valueOf(rs.getFloat(3)));
                
            }
            
           
            
            
        } catch (Exception e) {
            System.out.println("erro busca nome equi combo "+e);
        }finally{
            ConnectionFactory.closeConnection(con, ps, rs);
        }
        
    }
    
    public void popular_combo_lubrificantes(){
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        List lista = new ArrayList();
        
        try {
            ps = con.prepareStatement("SELECT * FROM public.lubrificantes order by nome_lub;");
            rs = ps.executeQuery();
            
            while(rs.next()){
                lista.add(rs.getString(2));
            }
            DefaultComboBoxModel defaultComboBox = new DefaultComboBoxModel(lista.toArray());
            combo_lubrificante2.setModel(defaultComboBox);
            
            
        } catch (Exception e) {
            System.out.println("erro popula combo "+e);
        }finally{
            ConnectionFactory.closeConnection(con, ps, rs);
            
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        combo_lubrificante2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campo_quantidade2 = new javax.swing.JTextField();
        botao_adicionar_estoque = new javax.swing.JButton();
        botao_remover_estoque = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        label_ultimo_estoque = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botao_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ENGEMAQ - ESTOQUE LUBRIFICANTE");
        getContentPane().setLayout(null);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("LUBRIFICANTE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 20, 130, 25);

        combo_lubrificante2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_lubrificante2ItemStateChanged(evt);
            }
        });
        getContentPane().add(combo_lubrificante2);
        combo_lubrificante2.setBounds(160, 20, 210, 25);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ESTOQUE ATUAL:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 50, 130, 25);
        getContentPane().add(campo_quantidade2);
        campo_quantidade2.setBounds(160, 120, 210, 24);

        botao_adicionar_estoque.setText("ADICIONAR AO ESTOQUE");
        botao_adicionar_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_adicionar_estoqueActionPerformed(evt);
            }
        });
        getContentPane().add(botao_adicionar_estoque);
        botao_adicionar_estoque.setBounds(120, 160, 180, 32);

        botao_remover_estoque.setText("REMOVER DO ESTOQUE");
        botao_remover_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_remover_estoqueActionPerformed(evt);
            }
        });
        getContentPane().add(botao_remover_estoque);
        botao_remover_estoque.setBounds(120, 200, 180, 32);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("QUANTIDADE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 120, 130, 25);

        label_ultimo_estoque.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        label_ultimo_estoque.setText("200");
        getContentPane().add(label_ultimo_estoque);
        label_ultimo_estoque.setBounds(160, 50, 210, 25);

        jLabel8.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AJUSTE DE ESTOQUE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 90, 380, 20);

        botao_sair.setText("SAIR");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair);
        botao_sair.setBounds(170, 250, 77, 32);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_adicionar_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_adicionar_estoqueActionPerformed
        // TODO add your handling code here:
        if (campo_quantidade2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"para ajustar o estoque defina a quantidade");
        }else{
            //soma do estoque
            float estoque, inclusao, resultado;
                estoque = Float.parseFloat(label_ultimo_estoque.getText());
                inclusao = Float.parseFloat(campo_quantidade2.getText());
                resultado = estoque + inclusao;
            //
            
                  Connection con = ConnectionFactory.getConnection(); //abrindo a conexao
            PreparedStatement ps = null;
            try {
                ps = con.prepareStatement("UPDATE public.lubrificantes\n" +
"	SET quantidade_lub=?\n" +
"	WHERE nome_lub = ?;");
                ps.setFloat(1,resultado);
                ps.setString(2, combo_lubrificante2.getSelectedItem().toString());
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Realizado com Sucesso!");
                campo_quantidade2.setText(null);
            } catch (Exception e) {
                e.printStackTrace();
            }finally{
                ConnectionFactory.closeConnection(con, ps);
            }
        }
       
    }//GEN-LAST:event_botao_adicionar_estoqueActionPerformed

    private void combo_lubrificante2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_lubrificante2ItemStateChanged
        buscar_estoque_lub();
    }//GEN-LAST:event_combo_lubrificante2ItemStateChanged

    private void botao_remover_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_remover_estoqueActionPerformed
        if (campo_quantidade2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"para ajustar o estoque defina a quantidade");
        }else{
            //soma do estoque
            float estoque, remocao, resultado;
                estoque = Float.parseFloat(label_ultimo_estoque.getText());
                remocao = Float.parseFloat(campo_quantidade2.getText());
                resultado = estoque - remocao;
            //
            
                  Connection con = ConnectionFactory.getConnection(); //abrindo a conexao
            PreparedStatement ps = null;
            try {
                ps = con.prepareStatement("UPDATE public.lubrificantes\n" +
"	SET quantidade_lub=?\n" +
"	WHERE nome_lub = ?;");
                ps.setFloat(1,resultado);
                ps.setString(2, combo_lubrificante2.getSelectedItem().toString());
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Realizado com Sucesso!");
                campo_quantidade2.setText(null);
            } catch (Exception e) {
                e.printStackTrace();
            }finally{
                ConnectionFactory.closeConnection(con, ps);
            }
        }
    }//GEN-LAST:event_botao_remover_estoqueActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque_lubrificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque_lubrificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque_lubrificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque_lubrificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque_lubrificante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_adicionar_estoque;
    private javax.swing.JButton botao_remover_estoque;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_quantidade2;
    private javax.swing.JComboBox<String> combo_lubrificante2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_ultimo_estoque;
    // End of variables declaration//GEN-END:variables
}
